package com.example.javaquiz
object QuestionController {
    fun getQuestion(): ArrayList<QuestionModel> {
        val QuestionList = ArrayList<QuestionModel>()

        val q1 = QuestionModel(
            1,
            "Who is known as father of Java Programming Language?",
            "James Gosling",
            "M. P Java",
            "Charel Babbage",
            "Blais Pascal",
            1
        )
        QuestionList.add(q1)
        val q2 = QuestionModel(
            2,
            "In java control statements break, continue, return, try-catch-finally and assert belongs to?",
            "Selection statements",
            "Loop Statements",
            "Transfer statements",
            "Pause statement",
            3
        )
        QuestionList.add(q2)
        val q3 = QuestionModel(
            3,
            "Which provides runtime environment for java byte code to be executed?",
            "JRE",
            "JVM",
            "JDK",
            "JAVAC",
            2
        )
        QuestionList.add(q3)
        val q4 = QuestionModel(
            4,
            "What is byte code in Java?",
            "Code generated by a Java compiler",
            "Code generated by a Java Virtual Machine",
            "Name of Java source code file",
            "Name of Java source code file",
            1
        )
        QuestionList.add(q4)
        val q5 = QuestionModel(
            5,
            "Which of the following are not Java keywords ?",
            "double",
            "switch",
            "then",
            "instanceof",
            3
        )
        QuestionList.add(q5)
        val q6 =
            QuestionModel(6, "Which of these have highest precedence?", "()", "++", "*", ">>", 1)
        QuestionList.add(q6)
        val q7 = QuestionModel(
            7,
            "Which of these is returned by operator '&' ?",
            "Integer",
            "Character",
            "Boolean",
            "Float",
            2
        )
        QuestionList.add(q7)
        val q8 = QuestionModel(
            8,
            "Data type long literals are appended by _____",
            "Uppercase L",
            "Lowercase L",
            "Long",
            "Both option one and two",
            4
        )
        QuestionList.add(q8)
        val q9 = QuestionModel(
            9,
            "Which variables are created when an object is created with the use of the keyword 'new' and destroyed when the object is destroyed?",
            "Local variables",
            "Instance variables",
            "Class Variables",
            "Static variables",
            2
        )
        QuestionList.add(q9)
        val q10 = QuestionModel(
            10,
            "Java language was initially called as ________",
            "Sumatra",
            "J++",
            "Oak",
            "Pine",
            3
        )
        QuestionList.add(q10)
        val q11 = QuestionModel(
            11,
            "What is garbage collection in the context of Java?",
            "Java deletes all unused java files on the system.",
            "Memory used by the object with no reference is automatically reclaimed.",
            "The JVM cleans output of Java program with error.",
            "Any unused package in a program automatically gets deleted.",
            2
        )
        QuestionList.add(q11)
        val q12 = QuestionModel(
            12,
            "Which one is a template for creating different objects ?",
            "An Array",
            "A class",
            "Interface",
            "Method",
            2
        )
        QuestionList.add(q12)
        val q13 = QuestionModel(
            13,
            "Which symbol is used to contain the values of automatically initialized arrays?",
            "Brackets",
            "Braces",
            "Parentheses",
            "Comma",
            2
        )
        QuestionList.add(q13)
        val q14 = QuestionModel(
            14,
            "Which one is true about a constructor ?",
            "A constructor must have the same name as the class it is declared within.",
            "A constructor is used to create objects.",
            "A constructor may be declared private",
            "All of the above",
            4
        )
        QuestionList.add(q14)
        val q15 = QuestionModel(
            15,
            "Which of these operators is used to allocate memory to array variable in Java?",
            "alloc",
            "malloc",
            "new malloc",
            "new",
            4
        )
        QuestionList.add(q15)
        return QuestionList
    }
    }
